apiVersion: v1
kind: Service
metadata:
  name: nginx-nfs-service      
spec:
  selector:                  
    name: nginx-nfs-pod
  ports:
  - name: web
    port: 8080               
    targetPort: 8080
  