apiVersion: v1
kind: Pod
metadata:
  name: busybox-nfs-pod 
  labels:
    name: busybox-nfs-pod
spec:
  containers:
  - name: busybox-nfs-pod
    image: busybox 
    command: ["sleep", "60000"]
    volumeMounts:
    - name: nfsvol-2 
      mountPath: /usr/share/busybox  
      readOnly: false
  securityContext:
    supplementalGroups: [100003] 
    privileged: false
  volumes:
  - name: nfsvol-2
    persistentVolumeClaim:
      claimName: nfs-pvc