echo "****************************************************"
echo "* INSTALL AUTO TERMINEE                            *"
echo "*                                                  *"
echo "* - Modifier le mot de passe root                  *"
echo "* - rebooter via vagrant reload                    *"
echo "* - reconfigurer VBox via les commandes suivantes: *"
echo "*      cd /opt/VBox*/init                          *"
echo "*      ./vboxadd setup                             *"
echo "****************************************************"